apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-db-secret
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: wallabag-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: shared-postgres-username
  - secretKey: password
    remoteRef:
      key: shared-postgres-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-secret
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: wallabag-secret
    creationPolicy: Owner
  data:
  - secretKey: secret-key
    remoteRef:
      key: wallabag-secret-key
