apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.homelab.lastsector.lan"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.homelab.lastsector.lan"
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-internal-tls
      allowedRoutes:
        namespaces:
          from: All
