apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: shared-services
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: shared-postgres-username
  - secretKey: password
    remoteRef:
      key: shared-postgres-password
