apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/CedricLphn/homelab.git
    targetRevision: main
    path: apps/miniflux/base
  destination:
    server: https://kubernetes.default.svc
    namespace: miniflux
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
