apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radicale
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/CedricLphn/homelab.git
    targetRevision: main
    path: apps/radicale/base
  destination:
    server: https://kubernetes.default.svc
    namespace: radicale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
