apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secret
  namespace: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: karakeep-secret
    creationPolicy: Owner
  data:
    - secretKey: nextauth-secret
      remoteRef:
        key: karakeep-nextauth-secret
    - secretKey: meili-master-key
      remoteRef:
        key: karakeep-meili-master-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-oidc-secret
  namespace: karakeep
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: karakeep-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: karakeep-oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: karakeep-oidc-client-secret
    - secretKey: wellknown-url
      remoteRef:
        key: karakeep-oidc-wellknown-url
