apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karakeep-ingress
  namespace: karakeep
  annotations:
    tailscale.com/hostname: karakeep
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - karakeep
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karakeep
                port:
                  number: 3000
