apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.tail<your-tailnet-id>.ts.net

  oidc.config: |
    name: Authelia
    issuer: https://auth.example.com
    clientID: $argocd-oidc-secret:clientID
    clientSecret: $argocd-oidc-secret:clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
    requestedIDTokenClaims:
      groups:
        essential: true

  admin.enabled: "true"

  server.insecure: "true"

  repositories: |
    - type: git
      url: https://github.com/your-username/homelab.git
