apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-admin-password
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cluster-secretstore
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: argocd-secret
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: admin.password
      remoteRef:
        key: argocd-admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cluster-secretstore
  target:
    name: argocd-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: argocd-oidc-client-id
    - secretKey: clientSecret
      remoteRef:
        key: argocd-oidc-client-secret
