apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: homelab-l2-announce
spec:
  serviceSelector:
    matchLabels:
      io.cilium/lb-l2-announce: "true"
  interfaces:
    - <NODE-NETWORK-INTERFACE>
  externalIPs: true
  loadBalancerIPs: true
