apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale-users
  namespace: radicale
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cluster-secretstore
  target:
    name: radicale-users
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: radicale-htpasswd
