apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secret
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: immich-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: immich-db-username
  - secretKey: password
    remoteRef:
      key: immich-db-password
