apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-secret
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: mealie-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: mealie-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-oidc-secret
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: mealie-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: mealie-oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: mealie-oidc-client-secret
    - secretKey: wellknown-url
      remoteRef:
        key: mealie-oidc-wellknown-url
